//
// Generated file, do not edit! Created by nedtool 5.0 from P_PDU.msg.
//

#ifndef __P_PDU_M_H
#define __P_PDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "D_PDU_m.h"
// }}

/**
 * Class generated from <tt>P_PDU.msg:27</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet P_PDU
 * {
 *     int id;
 *     D_PDU msg;
 * }
 * </pre>
 */
class P_PDU : public ::omnetpp::cPacket
{
  protected:
    int id;
    D_PDU msg;

  private:
    void copy(const P_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const P_PDU&);

  public:
    P_PDU(const char *name=nullptr, int kind=0);
    P_PDU(const P_PDU& other);
    virtual ~P_PDU();
    P_PDU& operator=(const P_PDU& other);
    virtual P_PDU *dup() const {return new P_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual D_PDU& getMsg();
    virtual const D_PDU& getMsg() const {return const_cast<P_PDU*>(this)->getMsg();}
    virtual void setMsg(const D_PDU& msg);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const P_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, P_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __P_PDU_M_H

